name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Calculate Artifact Name
        shell: bash
        run: |
          VERSION="${{ github.ref_name }}"
          CLEAN_VERSION="${VERSION#v}"
          
          ZIP_NAME="faerite-${CLEAN_VERSION}-${{ matrix.platform }}.zip"
          
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      # The ubuntu headless server requires UI libraries to compile a JavaFX app.
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Build with Maven
        run: mvn clean compile javafx:jlink

      - name: Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          jpackage --type app-image --runtime-image target/image --name Faerite --module faerite/faerite.Main --dest out
          cd out && zip -r ../${{ env.ZIP_NAME }} Faerite

      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          jpackage --type app-image --runtime-image target/image --name Faerite --module faerite/faerite.Main --dest out
          Compress-Archive -Path out/Faerite -DestinationPath ${{ env.ZIP_NAME }}

      - name: Package Mac
        if: matrix.os == 'macos-latest'
        run: |
          jpackage --type app-image --runtime-image target/image --name Faerite --module faerite/faerite.Main --dest out
          cd out && zip -r ../${{ env.ZIP_NAME }} Faerite.app

      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: ${{ env.ZIP_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Fetch Tags
        run: git fetch --tags --force

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Extract release message
        id: tag_data
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          TITLE=$(git tag -l --format='%(contents:subject)' $REF_NAME)
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          
          echo "BODY<<EOF" >> $GITHUB_ENV
          git tag -l --format='%(contents:body)' $REF_NAME >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TITLE }}
          body: ${{ env.BODY }}
          generate_release_notes: true
          files: artifacts/*.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

